sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
branches:
  only:
    - master
before_install:
  - npm i -g yarn-bin-fix
script:
  - yarn-bin-fix && yarn build
after_success:
  - yarn run semantic-release
